apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-#USER#-ingress
  namespace: #USER#
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"  
spec:
  rules:
  - host: #USER#.janjanjan.xyz
    http:
      paths:
      - backend:
          serviceName: app-#USER#-service-blue
          servicePort: 80      
  - host: #USER#-blue.janjanjan.xyz
    http:
      paths:
      - backend:
          serviceName: app-#USER#-service-blue
          servicePort: 80  
  - host: #USER#-green.janjanjan.xyz
    http:
      paths:
      - backend:
          serviceName: app-#USER#-service-green
          servicePort: 80
